name: conver latex to pdf 
on: 
  push:
    branches:
      - main
  pull_request:
jobs:
  build_latex:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "*.tex"
          glob_root_file: true

      - name: Add & Commit
        if: github.event_name == 'push'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: '*.pdf'

      - name: generate PDF files as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: "*.pdf"
