name: conver latex to pdf 
on: 
  push:
    branches:
      - main
  pull_request:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "*.tex"
          glob_root_file: true

      - name: Add & Commit
        if: github.event_name == 'push'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add "*.pdf"
          git commit -m 'commit PDFs'

      - name: generate PDF files as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: "*.pdf"
